config/routes.rb
WildeBier::Application.routes.draw do
  
  get "static_pages/home"

  get "static_pages/help"

  resources :beers
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/admin',   to: 'static_pages#admin'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  attr_accessible :description, :name, :style
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :admin, :password, :password_confirmation
  attr_accessible :fb_user_id, :fb_status, :fb_access_token, :fb_signed_request, :fb_expires
  has_secure_password
  
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

# removed so we can update via without pw fields
# TODO - keep pw validation for secure stuff, move nonsecure to profile table
#  validates :password,  length: { minimum: 6 }
#  validates :password_confirmation, presence: true
  
 
  
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.json
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(params[:beer])

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render json: @beer, status: :created, location: @beer }
      else
        format.html { render action: "new" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.json
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      
      sign_in user
      
      respond_to do |format|
        format.html { redirect_back_or root_path }
        format.json { render json:  { :id => user.id, 
                                    :first_name => user.first_name, 
                                    :last_name => user.last_name,
                                    :email=> user.email,
                                    :remember_token=> user.remember_token
                                  }
                     }
      end
      
      
    else
      
      respond_to do |format|
        format.html { #render'new' }
           flash.now[:error] = 'Invalid email/password combination'
           render 'new'
        }
        
        
        format.json { render :json => { :error => 'Invalid email/password combination' }, :status => 422 }

      end
        
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  #before_filter :signed_in_user,  only: [:home]
  before_filter :admin_user, only: [:admin]

  
  def home
  end

  def help
  end
  
  def admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    
  before_filter :signed_in_user,  only: [:home]
  #TODO find way to update user without them being logged in - so we can update fb status, then log them in
  # =>    but restrict profile updates to only logged in users
  before_filter :correct_user,   only: [:edit, :show]
 
  def index
    
    if params[:fbid]
      fbid = params[:fbid]
      # TODO if we find more than one, do something about dupes
      @users = User.find(:first, :conditions => ['fb_user_id = ?', fbid] )
      render json: @users
    else
      @users = User.paginate(page: params[:page])
    end
    
  end
  
  def show
    if params[:id]
      @user = User.find(params[:id])
    end
      
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
    
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to WILDEBIER"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    
    # TODO - fix so we only sign in:
    #         a) existing user in db whose fb credentials we just got, or
    #         b) current user who is updating their profile
    if !signed_in?
      sign_in @user
    end
    
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      
      logger.debug ' ############### current_user?=' + current_user?(@user).to_s
      if current_user?(@user)
        sign_in @user
      end
      
      # TODO - make so we redirect from edit page, we do not from in-page ajax request - e.g. to get fb details
      
      if request.xhr?
        logger.debug '++ is request.xhr'
        render :json => {
          #:location => url_for(:controller => 'jobs', :action => 'index'),
          :flash => {:notice => "Hello"}
        }
      else
        redirect_to @user
      end
      
    else
      render 'edit'
    end
    
  end
  
  private
  
      def correct_user
        @user = User.find(params[:id])
        logger.debug "#############################  in correct_user";
        logger.debug 'current_user?=' + current_user?(@user).to_s
        logger.debug 'current_user.admin?=' + current_user.admin?.to_s
        
        if !current_user?(@user) && !current_user.admin?
          redirect_to(root_path)
        end
        
        #redirect_to(root_path) unless current_user?(@user) || @user.admin?
      end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
   user == current_user
  end
  
  def current_user=(user)
    @current_user=user
  end
  
  def admin_user
    logger.debug ' ########### admin_user? ' + current_user.admin?.to_s
    unless current_user.admin?
      redirect_to root_url
    end
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def store_location
    session[:return_to] = request.url
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  

  
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Style</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beers.each do |beer| %>
  <tr>
    <td><%= beer.name %></td>
    <td><%= beer.style %></td>
    <td><%= beer.description %></td>
    <td><%= link_to 'Show', beer %></td>
    <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
    <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beer', new_beer_path %>

<%= link_to 'JSON Beer', "beers.json" %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beer.name %>
</p>

<p>
  <b>Style:</b>
  <%= @beer.style %>
</p>

<p>
  <b>Description:</b>
  <%= @beer.description %>
</p>


<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "WILDE BIER", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if current_user && current_user.admin? %>
            <li><%= link_to "Beers", beers_path %></li>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                My Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Profile", current_user %></li>
                <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>WildeBier</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= requirejs_include_tag("application").gsub("/assets/application","application").html_safe %>
  <!-- javascript_include_tag "application" -->
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "bootstrap-responsive", :media => "all" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<% if !(params[:controller] == 'static_pages' && params[:action] == 'home') %>
    <%= render 'layouts/header' %>
<% end %> 

<div id="app-main" class="container row-fluid">
    <%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg|
        logger.debug msg %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/admin.html.erb
<div class="row span8">
    <div><h1>WildeBier ADMIN page</h1></div>
    <div><%= link_to "USERS", users_path %></div>
    <div><%= link_to "BEERS", beers_path %></div>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
    <!-- pass rails user data into javascript -->
    <script id="rails_user_data" type="text/json" >
        <%= current_user.to_json %>
    </script>
 
 <!--   
    <div id="list" class="row-fluid"></div>
    
    <div id="listHolder"></div>
</div>
-->
<!--
<%= debug(User.find_by_remember_token(cookies[:remember_token])) if Rails.env.development? %>
-->

app/views/users/_user.html.erb
<li>
  <%= link_to user.first_name + ' ' + user.last_name, user %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :admin %>
      <%= f.check_box :admin %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

		<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.first_name) %>
 <div class="row-fluid">
        <div class="title span8">
            <h1>
                 <%= @user.first_name %> <%= @user.last_name %>
            </h1>

        </div>
    </div>
<div class="row">
    <div class="span4 offset2"><%=@user.first_name %></div>
</div>
<div class="row">
    <div class="span4 offset2"><%=@user.last_name %></div>
</div>
<div class="row">
    <div class="span4 offset2"><%=@user.email %></div>
</div>
<% if current_user || @user.admin %>
<div class="row">
    <div class="span4 offset2"><ADMIN GUY><%= link_to( 'EDIT', edit_user_path )%> </div>
</div>
<% end %>